[platformio]
default_envs = nodemcu-32s

[common]
platform = espressif32
framework = espidf
board_build.f_cpu = 240000000L
monitor_speed = 115200
upload_speed = 460800
lib_deps =
    jgromes/RadioLib
lib_ignore =
    RadioLib
build_flags =
    -D LOG_LEVEL=3
    -include include/RadioLibCompat.h
    -D RADIOLIB_EXCLUDE_AFSK=1
    -D RADIOLIB_EXCLUDE_AX25=1
    -D RADIOLIB_EXCLUDE_HELLSCHREIBER=1
    -D RADIOLIB_EXCLUDE_MORSE=1
    -D RADIOLIB_EXCLUDE_PAGER=1
    -D RADIOLIB_EXCLUDE_RTTY=1
    -D RADIOLIB_EXCLUDE_SSTV=1
    -D RADIOLIB_EXCLUDE_FSK4=1
    -D RADIOLIB_EXCLUDE_APRS=1
    -D RADIOLIB_EXCLUDE_LORAWAN=1
    -D RADIOLIB_EXCLUDE_BELL=1
    -D RADIOLIB_EXCLUDE_ADSB=1
    -D RADIO_FREQUENCY_MHZ=2445.0
    -D RADIO_BANDWIDTH_KHZ=812.5
    -D RADIO_SPREADING_FACTOR=7
    -D RADIO_CODING_RATE=5
    -D RADIO_SYNC_WORD=0x12
    -D RADIO_TX_POWER_DBM=2
    -D RADIO_PREAMBLE_LEN=12
    -D RADIO_TX_INTERVAL_MS=10000

[env:nodemcu-32s]
extends = common
board = nodemcu-32s
board_build.cmake_extra_args =
    -DNAV_PIO_ENV=nodemcu-32s
    -DSDKCONFIG_DEFAULTS=sdkconfig.defaults.nodemcu-32s
build_flags =
    ${common.build_flags}
    -D BOARD_NAME=\"NodeMCU-32S\"
    -D TARGET_NODEMCU_32S=1
    -D PIN_LORA_SCK=18
    -D PIN_LORA_MISO=19
    -D PIN_LORA_MOSI=23
    -D PIN_LORA_CS=5
    -D PIN_LORA_RST=27
    -D PIN_LORA_BUSY=26
    -D PIN_LORA_DIO1=25
    -D PIN_LORA_DIO2=-1
    -D PIN_LORA_DIO3=-1
    -D PIN_GPS_RX=16
    -D PIN_GPS_TX=17
    -D PIN_I2C_SDA=21
    -D PIN_I2C_SCL=22

[env:esp32-s3-devkitc-1]
extends = common
board = esp32-s3-devkitc-1
board_build.cmake_extra_args =
    -DNAV_PIO_ENV=esp32-s3-devkitc-1
    -DSDKCONFIG_DEFAULTS=sdkconfig.defaults.esp32-s3-devkitc-1
build_flags =
    ${common.build_flags}
    -D BOARD_NAME=\"ESP32-S3-DEVKITC-1\"
    -D PIN_LORA_SCK=12
    -D PIN_LORA_MISO=13
    -D PIN_LORA_MOSI=11
    -D PIN_LORA_CS=10
    -D PIN_LORA_RST=9
    -D PIN_LORA_BUSY=8
    -D PIN_LORA_DIO1=7
    -D PIN_LORA_DIO2=6
    -D PIN_LORA_DIO3=15
    -D PIN_GPS_RX=18
    -D PIN_GPS_TX=17
    -D PIN_I2C_SDA=4
    -D PIN_I2C_SCL=5
