if(NOT DEFINED REPLAY_EXE)
    message(FATAL_ERROR "REPLAY_EXE is required")
endif()
if(NOT DEFINED EVENTS)
    message(FATAL_ERROR "EVENTS is required")
endif()
if(NOT DEFINED OUT_DIR)
    message(FATAL_ERROR "OUT_DIR is required")
endif()

file(REMOVE_RECURSE "${OUT_DIR}")
execute_process(
    COMMAND "${REPLAY_EXE}" --events "${EVENTS}" --out-dir "${OUT_DIR}" --node-id 0 --pretty
    WORKING_DIRECTORY "${WORK_DIR}"
    RESULT_VARIABLE replay_result
    OUTPUT_VARIABLE replay_stdout
    ERROR_VARIABLE replay_stderr
)
if(NOT replay_result EQUAL 0)
    message(FATAL_ERROR "nav_replay failed:\n${replay_stdout}\n${replay_stderr}")
endif()

set(solution_path "${OUT_DIR}/solution.csv")
if(NOT EXISTS "${solution_path}")
    message(FATAL_ERROR "missing solution.csv: ${solution_path}")
endif()
file(STRINGS "${solution_path}" solution_lines)
list(LENGTH solution_lines solution_line_count)
if(solution_line_count LESS 2)
    message(FATAL_ERROR "solution.csv has no data rows")
endif()
math(EXPR final_index "${solution_line_count} - 1")
list(GET solution_lines "${final_index}" final_line)
string(REPLACE "," ";" final_fields "${final_line}")
list(LENGTH final_fields final_field_count)
if(final_field_count LESS 25)
    message(FATAL_ERROR "solution.csv final row has too few fields: ${final_line}")
endif()

list(GET final_fields 2 final_mode)
list(GET final_fields 3 final_solution)
list(GET final_fields 4 final_source)
list(GET final_fields 10 final_anchors)
list(GET final_fields 17 final_rms)
list(GET final_fields 22 final_reject)

if(DEFINED EXPECT_MODE AND NOT final_mode STREQUAL EXPECT_MODE)
    message(FATAL_ERROR "expected mode ${EXPECT_MODE}, got ${final_mode}")
endif()
if(DEFINED EXPECT_SOLUTION AND NOT final_solution STREQUAL EXPECT_SOLUTION)
    message(FATAL_ERROR "expected solution ${EXPECT_SOLUTION}, got ${final_solution}")
endif()
if(DEFINED EXPECT_SOURCE AND NOT final_source STREQUAL EXPECT_SOURCE)
    message(FATAL_ERROR "expected source ${EXPECT_SOURCE}, got ${final_source}")
endif()
if(DEFINED EXPECT_REJECT AND NOT final_reject STREQUAL EXPECT_REJECT)
    message(FATAL_ERROR "expected reject ${EXPECT_REJECT}, got ${final_reject}")
endif()
if(DEFINED EXPECT_ANCHORS AND NOT final_anchors STREQUAL EXPECT_ANCHORS)
    message(FATAL_ERROR "expected anchors ${EXPECT_ANCHORS}, got ${final_anchors}")
endif()
if(DEFINED MAX_RMS)
    if(NOT final_rms LESS_EQUAL MAX_RMS)
        message(FATAL_ERROR "expected residual RMS <= ${MAX_RMS}, got ${final_rms}")
    endif()
endif()

if(DEFINED EXPECT_LOG)
    set(log_path "${OUT_DIR}/logs.txt")
    if(NOT EXISTS "${log_path}")
        message(FATAL_ERROR "missing logs.txt: ${log_path}")
    endif()
    file(READ "${log_path}" logs_text)
    string(FIND "${logs_text}" "${EXPECT_LOG}" log_index)
    if(log_index EQUAL -1)
        message(FATAL_ERROR "expected logs to contain '${EXPECT_LOG}'")
    endif()
endif()

if(DEFINED EXPECT_COMPARE_REPORT AND EXPECT_COMPARE_REPORT)
    set(report_txt "${OUT_DIR}/compare_report.txt")
    set(report_json "${OUT_DIR}/compare_report.json")
    if(NOT EXISTS "${report_txt}")
        message(FATAL_ERROR "missing compare_report.txt: ${report_txt}")
    endif()
    if(NOT EXISTS "${report_json}")
        message(FATAL_ERROR "missing compare_report.json: ${report_json}")
    endif()
    file(READ "${report_txt}" report_text)
    string(FIND "${report_text}" "pass=true" report_pass_index)
    if(report_pass_index EQUAL -1)
        message(FATAL_ERROR "compare report did not pass:\n${report_text}")
    endif()
    string(FIND "${report_text}" "rows_compared=" report_rows_index)
    if(report_rows_index EQUAL -1)
        message(FATAL_ERROR "compare report missing rows_compared:\n${report_text}")
    endif()
endif()
